### ISSUE TITLE
Use Arduino Leonardo Board instead

### ISSUE THREAD

**Issue by cbDragon** [BdF-LabSec/kpn532#1]
Hey guys, I am really appreciated with your great work about the PN532. I am a novice in Arduino field. However, I wonder if I use Arduino Leonardo to do the experiment, anything need to be changed? For example, the wire connection I found in the elechouse pdf may be different between this two development board.

**Comment by gentilkiwi** [comment]
I never used an Arduino Leonardo board before, so cannot be sure... but as boards follow Arduino connector standards:

- SPI (CLK, MOSI & MISO) are on same SPI pins (13, 11 & 12) ;
- Interrupts are on same interruptable pins (2 & 3) ;

it _should_ work.

## SPI
![image](https://github.com/BdF-LabSec/kpn532/assets/2307945/329a236f-a9c7-4be9-8aa9-61acdc6a9c26)
> https://docs.arduino.cc/language-reference/en/functions/communication/SPI/

## Interrupts
![image](https://github.com/BdF-LabSec/kpn532/assets/2307945/abc24d0f-466c-43ed-8fc4-ab1c959e9332)
> https://docs.arduino.cc/language-reference/en/functions/external-interrupts/attachInterrupt/

**Comment by cbDragon** [comment]
Thanks so much, I try to follow your advices.

**Comment by gentilkiwi** [comment]
In fact the documentation is wrong, SPI pins are not 10/11/12, you must take a look at the ICSP header
![image](https://github.com/user-attachments/assets/9aa333f6-0df0-43df-af25-2b6e9eb035b9)

https://content.arduino.cc/assets/Pinout-Leonardo_latest.pdf

I sent a message on https://github.com/arduino/Arduino/issues/11470

(and I confirm it works on Leonardo :))

**Comment by gentilkiwi** [comment]
It seems referenced here:
- https://github.com/arduino/reference-en/issues/974
- https://github.com/arduino/reference-en/pull/976

Opened since ~1 year despite a pull-request :(
